id: AB04C7A5B
base_file: f8999.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:59:57.171649
  last_modified_at: 2022-05-30 20:59:57.171656
